net1_wifi_ssid="dd"
net1_wifi_password="MikkeMus92"
stats_uri="https://myatp-dbname.adb.eu-frankfurt-1.oraclecloudapps.com/ords/iot/iotv1/iotstats/"
get_ip_uri="https://api.ipify.org?format=json"
siteid="fl"
use_ntp="True"
tp_server="no.pool.ntp.org"
debug_level="4"
loop_sleep_time="10"
